services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "sermaluc"
      POSTGRES_DB: ${DB_NAME}
    container_name: desafio
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql